# Generated by Django 4.1.3 on 2022-11-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('position', models.TextField()),
                ('skills', models.TextField()),
                ('describtion', models.TextField()),
                ('qualification', models.TextField()),
            ],
        ),
    ]
