# Generated by Django 4.1.3 on 2022-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_jops'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCompanies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('size', models.IntegerField()),
                ('head', models.TextField()),
                ('about', models.TextField()),
                ('based', models.TextField()),
                ('products', models.TextField()),
                ('website', models.TextField()),
                ('gmail', models.CharField(max_length=30, unique=True)),
                ('password', models.TextField()),
                ('phone', models.TextField()),
                ('type', models.TextField()),
                ('logo', models.ImageField(upload_to='media/logo')),
            ],
        ),
    ]
