# Generated by Django 4.1.3 on 2022-12-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_appcompanies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField()),
                ('type', models.TextField()),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('post_date', models.DateField()),
                ('responsibility', models.TextField()),
                ('basic_qualification', models.TextField()),
                ('preffered_qualification', models.TextField()),
                ('companie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.appcompanies')),
            ],
        ),
    ]
