# Generated by Django 4.1.3 on 2022-12-06 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_job_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply_jop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('skills', models.TextField()),
                ('jop_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.job_posts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.signupuser')),
            ],
        ),
    ]
