# Generated by Django 4.1.3 on 2023-01-31 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_apply_jop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('froms', models.IntegerField()),
                ('to', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='job_posts',
            name='post_date',
            field=models.DateField(auto_now=True),
        ),
    ]
