# Generated by Django 4.1.3 on 2023-01-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_follow_alter_job_posts_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('froms', models.EmailField(max_length=254)),
                ('to', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
