# Generated by Django 4.1.3 on 2023-02-14 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_userfollow_delete_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='posts')),
                ('companie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.appcompanies')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App.signupuser')),
            ],
        ),
    ]
